### ISSUE TITLE
Love the idea but there is some issue

### ISSUE THREAD

**Issue by danishrp** [jwritz/s1lent_lottery#2]
There is a couple of issues.

Pool fails on line 457 with an arithmetic nil value local pool

And atm fails when trying to buy a ticket on line 517 with a arithmetic nil value on field ?

**Comment by jwritz** [comment]
Could you attach your s1lent_lottery_config.lua?

**Comment by danishrp** [comment]
Default config to be honest.

**Comment by danishrp** [comment]
The error happens both with amt and pool, 457 is pool and 517 is amt - when trying to buy a ticket.

**Comment by jwritz** [comment]
Did you update from a previous version? If so make sure you followed the [Updating](https://github.com/jwritz/s1lent_lottery/wiki/Updating) instructions.
(Make sure your database has the needed columns)

**Comment by danishrp** [comment]
No clean install of current version

**Comment by jwritz** [comment]
1. Does your database have the following:
    * table called 'lottery_drawings' containing columns uniqueID, id, date, numbers, and pool
    * table called 'lottery_tickets' containing columns id, identifier, drawingUniqueID, drawingID, numbers, isDrawn, prize, drawDate, and drawTime

2. What exactly are you doing when the errors occur? Which drawing (does it happen for all of them)? Does it happen when selecting which drawing, when selecting numbers, etc.

**Comment by jwritz** [comment]
I believe I found the issue. If you create a new row in the 'lottery_drawings' table in your database with the following values it should work. The default pool lottery is in the config but is not included in the .sql file.

- uniqueID: wednesday_pool_lotto
- id: 0
- date: 10/23/2019
- pool: 500
(numbers column should be (NULL))

**Comment by danishrp** [comment]
Ah ill try it out and see if that helps, not sure since i removed the wednesday pool since it was not in the sql, ill try it out once more to see if it can  get it to work or it dos the same  stunt.

**Comment by danishrp** [comment]
Hmm got it working and then it did something so with the resource enabled the server wont start, never tryed that before haha

**Comment by jwritz** [comment]
Are you still having the issue? If so, are there any error messages that print to the server console? If the wednesday_pool_lotto is removed from config or added to database (so it either exists or does not exist in both the config and database), does an error still occur?

**Comment by jwritz** [comment]
I'm closing this issue since it has been inactive for over a year. Please reopen if you continue having this issue.
