### ISSUE TITLE
How can I put it to work with my country date, Brazil.

### ISSUE THREAD

**Issue by shyricaus** [jwritz/s1lent_lottery#5]
How can I put it to work with my country date, Brazil.

**Comment by jwritz** [comment]
Replacing the `s1lent_lottery_server.lua` with this `.lua` file should change the format to DD/MM/YYYY [s1lent_lottery_server.zip](https://github.com/jwritz/s1lent_lottery/files/3864501/s1lent_lottery_server.zip)
Let me know if it works or does not work.
