### ISSUE TITLE
lottery drawings automatically?

### ISSUE THREAD

**Issue by xrtw** [jwritz/s1lent_lottery#8]
hello, is it possible to make lottery drawings automatically? because after a daily lotto, i need to edit other day (for example tomorrow), its not automatically

**Comment by jwritz** [comment]
Hello, changing the frequency to "daily" for the lottery drawing in the config file (`s1lent_lottery_config.lua`) should make an automatic daily drawing.
(See the example Daily Lotto drawing in the default config [here](https://github.com/jwritz/s1lent_lottery/blob/master/s1lent_lottery_config.lua))
